module.exports = {
    products: [
        {
            _id: '1',
            name: 'Melisa',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 10,
            brand: 'Herbapol',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Kminek',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 15,
            brand: 'Herbapol',
            rating: 3.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Mieta',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 22,
            brand: 'Herbapol',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Rumianek',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 13,
            brand: 'Herbapol',
            rating: 2.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Melisa',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 23,
            brand: 'Herbapol',
            rating: 5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Melisa',
            category: 'ziola',
            image: './images/produkt-1.jfif',
            price: 8,
            brand: 'Herbapol',
            rating: 4,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};